### ISSUE TITLE
Okno pisania SQL nie pojawia się i nie mózna go dodać

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#224]
np tak jak tutaj
brak przycisku dodania SQL'a
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/3fa6ab6a-4e25-480d-adb3-25e04162c458)

**Comment by KrzysztofDusko** [comment]
Przede wszystkim jakoś powinno się dodać pierwszy dokument np. po przypadkowanym skasowaniu całości albo nie pozwolić na kasowanie jedynego dokumentu.

**Comment by KrzysztofDusko** [comment]
fixed
