### ISSUE TITLE
DDL procedury netezza - pobiera treść z cache a nie bazy

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#225]
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/7621b8f7-1af6-4999-9f87-bca0b39081cf)

**Comment by KrzysztofDusko** [comment]
DDL pojedynczej procedury dla Netezzy odświeża za każdym razem cache
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/a1f8afc6-aeba-4dc2-9d90-8b7f6b1bfe74)
działa także w wyszukiwarce procedur
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/1ab581c7-d543-499a-b6db-98568dc226cd)
