### ISSUE TITLE
Jump to a wielkość liter (netezza)

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#228]
baza..tabela po użyciu Jump to(F6) nie działa prawidłowo jeśli użyto nazwy niezgodnej pod kontem wielkości liter dla Netezzy

**Comment by KrzysztofDusko** [comment]
poprawiono 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/79181ace-1ea3-408a-9ce0-17bbf90074e8)
