### ISSUE TITLE
Zamykanie dokumentu nie pyta o potwierdzenie

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#229]
łatwo przez przypadek zamknąć SQL - powinna być opcja z prośbą o potwierdzenie tej operacji.

**Comment by KrzysztofDusko** [comment]
dodano stosowną opcje do menu. Ale jej włączenie należy traktować jako eksperymentalne (opcja jest domyślnie wyłączona  - bo potrzebuje zebrać trochę diagnostyki aby upewnić się że to działa stabilnie)
