### ISSUE TITLE
Czy można zatwierdzić podpowiadanie kodu klawiszem entera a nie tylko tabulatorem ? 

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#232]

**Comment by KrzysztofDusko** [comment]
dodano stosowną opcję (domyślnie wyłączona) do ustawień jednak jej włączenie może spowodować niedogodności  polegające na tym że jak się chce dać faktycznie enter to nie może być na ekranie okna podpowiadania... Ogólnie polecam jednak zatwierdzać tabulatorem. 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/3adec003-567f-4d7e-b8be-7f09cd2b9dd2)
