### ISSUE TITLE
Brak zaznaczenia wybranych komórek w wyniku zapytania

### ISSUE THREAD

**Issue by elaslowska** [KrzysztofDusko/JustyBase#233]
W wyniku zapytania nie można zaznaczyć wybranych komórek i skopiować. Działa tylko kopiowanie wiersza lub całej tabeli.

**Comment by KrzysztofVl** [comment]
czy to nie dublem dla ? 
https://github.com/KrzysztofDusko/JustyBase/issues/219

**Comment by KrzysztofVl** [comment]
ponad to 
_Działa tylko kopiowanie wiersza lub całej tabeli._
tylko ? nie możesz skopiowac np. kilku wierszy lub kilka wartości jednak z nich ? 

np.
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/7768044d-b5fe-46a2-96f5-9cb2d99e531b)

lub
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/7ae3e7d8-b9b8-4c30-822e-0634c70b842e)

**Comment by elaslowska** [comment]
Zgadza się, zagadnienie się powiela z https://github.com/KrzysztofDusko/JustyBase/issues/219

**Comment by elaslowska** [comment]
temat wyczerpany
