### ISSUE TITLE
Ctrl+h – zamiana wyrażeń nie działa prawidłowo

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#236]
zamienia co drugi..
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/cf3f81ea-f349-4bb9-9d4e-4ac593cd8561)

**Comment by KrzysztofDusko** [comment]
temat poruszany tutaj
https://github.com/AvaloniaUI/AvaloniaEdit/issues/355

**Comment by KrzysztofDusko** [comment]
zrobiono obejście.
