### ISSUE TITLE
Dodanie opcji uznania połączenia za domyślne

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#239]
.. aby nowo dodana karta maiła już je wybrane
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/5b7cef88-c2ba-41a1-abce-7d66a9b95ba0)

**Comment by KrzysztofDusko** [comment]
poprawione, wybiera się to samo połączenie co dla aktualnie widocznej karty, a jak nie ma to pierwsze zdefiniowane połączenie
