### ISSUE TITLE
Variable default color is not readable enough

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#259]
and to close to comment 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/7827b5a3-a0e5-477b-b65e-3c782502fb1d)

**Comment by KrzysztofVl** [comment]
+ selection color ..

![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/c48c914b-8524-4cf1-8784-e6c4dec378ba)

**Comment by KrzysztofDusko** [comment]
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/40cb861c-e48b-4cf9-9484-8edce92915f0)

![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/a99ca5c4-1c65-4f00-9a55-e097a0d2de6f)
