### ISSUE TITLE
UI Colors/font size etc. should be more customizable

### ISSUE THREAD

**Issue by KrzysztofDusko** [KrzysztofDusko/JustyBase#264]

**Comment by andrzejchmiel3** [comment]
If I may have suggestion for default color, right now color of selection is almost the same as recurring text. Below i almost don't see what my selection is

![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/3741536c-4e47-424e-b259-f2ce52eb949d)

**Comment by KrzysztofDusko** [comment]
Do you have specific (RGB) suggestion what colors can be used for selection/recurring occurrences (be default)?

**Comment by andrzejchmiel3** [comment]
My suggestion :  100; 189; 183; 107 for same words style. Current normal selection color is fine, and shouldbe distinguishable with this same word style

**Comment by KrzysztofDusko** [comment]
added some more colro/font options (but ame words style is not customizable yet)
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/74871701-cf13-49da-8be7-6dfca8a7aa04)
