### ISSUE TITLE
Renaming snippets does not work

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#265]
There is not option to rename snippiets, even new snippets are "<NAME>" by default and this cannot be changed, which prevents me from making any new snippet.

**Comment by KrzysztofDusko** [comment]
fixed 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/1cf7e618-3f82-442f-b3bd-66a83ecc2906)
