### ISSUE TITLE
Autocompletion - quality of life suggestions

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#267]
1. Add autocompletion when something starts with comma, currently there is no autocompletion becasue of it
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/7d94b240-400b-438a-b8d7-27c8c8608ed6)
while everything is ok when there is space after comma:
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/20c971c2-ef2e-428d-bac8-638e7dcb7f1f)

2.  In some cases, autocompletion is more annoying than helpful, like typing numbers:
 ![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/082ea063-e52b-4b54-97b2-6b2fefb9569d)
(table cannot even start with number. It can contain numbers, thats why currently autocompletion works, but i guess not many people will try to benefit from current autocompletion of numbers)
My solution would be - in case of typing number, limit autocompletion to only snippets starting with that number

3. Limit database autocompletion, or delay it so it wont show immediately after typing single letter, like below. 
( My idea would be to show database autocompletion after typing >=3 letters. But there may be better solution like slight 0.3s delay)
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/127d3a0c-1e09-4e09-842d-3f25da942822)

4. Disable autocompletion in comments:
 (maybe excluding snippets)
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/b18567a2-3f02-473e-9edb-e907f49a81ca)

**Comment by KrzysztofDusko** [comment]
- [ ] #272
- [ ] #273 
- [ ] #274 
- [ ] #275

**Comment by KrzysztofDusko** [comment]
4.  in my opinien is feature ont bug.. Some usage scenarios benefit from that. I wont change this behavior at this point but maybe in the future i will change my mind
```sql
... PRODUCTION CODE ...
/* some additional/test code that should not be compiled in procedeure etc.
*/
```
Please check 1,2,3 and let my know is it fixed for you.
