### ISSUE TITLE
snippet not replacing whole part of what i wrote

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#268]
Steps how to recreate bug:
1. Choose any snippet, below for default "BETWEEN", but it seems to work in other types of snippets too
2. TYPE BETWE
(don't press tab, triggering snippet now would work as intended)
4. backspace, so we get BETW
5. type "E", so we get BETWE
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/7f7105bf-25f7-4a2e-89b1-7fc47de680e1)

6. tab. I'm getting:
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/2fab46a1-15eb-4d0b-bd7b-4dd1b9e54f06)

**Comment by KrzysztofDusko** [comment]
probably fixed.. 
 but please test this well especiali with conjunction with https://github.com/KrzysztofDusko/JustyBase/issues/266

**Comment by andrzejchmiel3** [comment]
Now it seems fine, thank you
