### ISSUE TITLE
double bracket puts cursor outside of brackets

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#269]
When typing opening bracket ( , we also got closing one ), but cursor moves after the closing one. For example, , typing 

> (asd 

gives us 

> ()asd

instead of 

> (asd)

 I think it worked like this before, but you accidentally changed it.

**Comment by KrzysztofDusko** [comment]
well this explains this comment :) 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/9eef93ff-3970-4058-a213-deb1bfb3f9cc)
FIXED
