### ISSUE TITLE
Autocompletion from subqueries does not work in semi-complicated subquery

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#270]
Example:

> select 
> tab1.kol1
> ,  tab2.
> from (select 1 as kol1)  as tab1
>         LEFT JOIN 
>         ( SELECT 1 as kol2 ,555 as NR  )   as tab2     ON tab2.kol2::CHAR(1) = tab1.kol1 ::CHAR(1) AND tab2.NR = 555

typing tab2. does not trigger autocompletion. This is as simple as it could get, so removing anything else makes it working as intended, but this combination of subqueries and join conditions somehow disables autocompletion

**Comment by KrzysztofDusko** [comment]
works
```SQL
SELECT * FROM
FROM (SELECT 1 AS KOL1) AS TAB1
LEFT JOIN (SELECT 1 AS KOL2 ,555 AS NR FROM JUST_DATA..DIMACCOUNT) AS TAB2 ON 
    TAB2.KOL2 = TAB1.KOL1
    AND TAB2.
```
works
```SQL
SELECT * FROM
FROM (SELECT 1 AS KOL1) AS TAB1
LEFT JOIN (SELECT 1 AS KOL2 ,555 AS NR FROM JUST_DATA..DIMACCOUNT) AS TAB2 ON 
    TAB2.KOL2 = TAB1.KOL1::INT
    AND TAB2.
```
**do not**
```SQL
SELECT * FROM
FROM (SELECT 1 AS KOL1) AS TAB1
LEFT JOIN (SELECT 1 AS KOL2 ,555 AS NR FROM JUST_DATA..DIMACCOUNT) AS TAB2 ON 
    TAB2.KOL2 = TAB1.KOL1::CHAR(1)
    AND TAB2.
```

**Comment by KrzysztofDusko** [comment]
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/cfa377fc-91a1-461b-9455-790440f4915e)

**Comment by KrzysztofDusko** [comment]
```\(.*\)(\s)+(?<alias>\w+)```

**Comment by KrzysztofDusko** [comment]
plase confirm with original SQL.

**Comment by andrzejchmiel3** [comment]
It works now correctly, thank you
