### ISSUE TITLE
Snippet parameters (or at least cursor position) for fast snippets?

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#276]
Right now, snippet parameters  ${} work for standard snippets, but not for fast snippets. As it is useful to have choice of cursor position in fast snippet, I propose integrating above parameter ${} to fast snippets. Or at least some kind of cursor position after snippet like ^ symbol used in other programs.

Example, i have fast snippet for word   like  --> like '%%' , but it is useful as long as cursor lands between %%, not at the end.

**Comment by KrzysztofDusko** [comment]
you can use 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/2f7c82d2-4973-4485-a3d7-3e4cd7b3afd1)
with 
```sql like '%${Caret}%'```
content
please let me know is that OK for you

**Comment by andrzejchmiel3** [comment]
Yes, this is fine, thank you
