### ISSUE TITLE
Change snippet shortcut (right sihft) or allow disabling it

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#277]
Right shift is unfortunate choice for snippet, it's too easy to accidentaly trigger it by using anything requiring shift right after word that was a snippet.

For example, I might have snippet @char as some shortcut, but as "char" it is frequently used word, I also may type "char(" which will accidentaly trigger snippet. 
Another example, default snippet @merge prevents me from typing something like "mergeLandR"

**Comment by KrzysztofDusko** [comment]
Do you have any default shortcut suggestion ?

**Comment by andrzejchmiel3** [comment]
Maybe similar, but harder to accidentally trigger:  ctrl+shift

**Comment by KrzysztofDusko** [comment]
ok, fixed
