### ISSUE TITLE
query log - auto scroll down

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#279]
Could Query log be by default scrolled down to last entry?

Right now, during run of multiple queries, I need to scroll down to see at which step series of queries actually are. And moment later, scroll down again, because it stays on previous position.
Or in case of error in one of queries, (example below), I need to look on log which query resulted in error, that will be on 'newest' log, which is on the bottom, and I need to scroll down to it everytime. 

select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1/0;select 1;select 1;select 1;

**Comment by KrzysztofDusko** [comment]
log can by sorted by date. I will make sort by date descending default option. 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/fd931e53-3b3e-4c76-8874-8b5e4d01b018)
