### ISSUE TITLE
Result filter by equal null is missleasing

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#280]
In exmaple below, in result filter, we can choose values to filter by (checkboxes). One of choices is NULL, but choosing it will result in no rows. It's accurate, those values are not equal NULL, we should choose 'is NULL' if we wanted NULLS. But the checkbox is missleasing, it makes us think we can choose it and it will show NULL values

And its even more missleasing if we unmark -6, then we also get results without NULLdespite 'not touching' NULLs

I'm suggesting change of mechanics, so tickbox near NULL will be treated as 'is null' instead of equal null.

select 1 
union all
select null
union all
select -6

![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/ab865c8a-bc58-46e2-a2c0-ab7a7e8490e8)

**Comment by KrzysztofDusko** [comment]
fixed
