### ISSUE TITLE
ctrl+shift shortcut for snippet does not work with active autocomplete window

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#282]
Shorcut does not work when autocomplete window is open.
Example: 
Then I type "c" (I have standard snippet for that, @c ), autocomplete window opens and shortcut does not work until I close autocomplete window (esc)

![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/2acdb041-525f-4ac9-9666-bb90f6c6cf45)

It's not a big deal, but requires me to think everytime I'm using snippet, If i have to press esc before cltr+shift, which of course is annoying

**Comment by KrzysztofDusko** [comment]
shortcut is changed now to classic Alt + C
