### ISSUE TITLE
Rows count limit - shows error when reaching limit

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#284]
When number of rows i results of query reaches limit (set in settings), it shows error like below, I think the message should be more friendly like "Rows limit reached"
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/0b0ebf67-ff43-41ae-a4fc-349d86e677a8)

**Comment by KrzysztofDusko** [comment]
this message comes from database system - not JubsyBase itseld. It not trivial to detect who canceled query 
 -you or  DB admin.
In some DB system Cancel operation takes some large amount of time - this i why i do not want to assume that time coincidence stop button v sthis window are related.
But posiible is to add additonal "Canceled" info.. but i dont think is really nedded.
