### ISSUE TITLE
Suggestions - Schema / File windows etc.

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#286]
In Polish, as there is too much I want to say without language misunderstanding

1. Search schema jest bardzo powiązane z samym schema, może lepiej jakby było złączone? (Podobnie jak search in files jest już częścią files)
2. "Add new" to dość nieintuicyjna nazwa na manager połączeń, może nazwać to "connections" ?
3.  Przycisk F6 na tabelę (albo F4 i jump to) ma sens tylko jak ma się gdzieś otwarty "Schema", dało by się żeby domyślnie on otwierał Schema?
4. W Files, u góry mamy search. Ale to działa tylko mając poniżej wybrane "Search" Dałoby się żeby to samo przeskakiwało na search? Albo najlepiej inaczej to rozwiązać, np. żeby okienko search pokazywało się tylko w zakładce search.
5. Wybór folderu do explorer / search - można tylko w jednym na raz szukać, przydatne by było móc dodać kilka folderów

**Comment by KrzysztofDusko** [comment]
1. w jaki sposób ? - tak aby wyszukiwanie działało faktycznie w schemacie ? Czy faktycznie jak w files. Nie bardzo czuję zalety bo obie opcje przecież uniemożliwią używania tych okienek na raz.. A okienka można ustawić przy sobie np .tak (jak ktoś nie chce ich widzieć na ekranie na raz) - dość podobny efekt co files
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/fdb58b92-06a4-42b8-945e-13e5f9db1893)
2. Cały ten panel jest dość roboczy i tak wymaga zmiany nazwy ale także zawartość jest słaba
- [ ] Connection setting - make this tool window better
3. - [ ] jump to should make visible schama tool windows
4. - [ ] Files tool should be modified
5. Temat można obecnie rozwiązać poprzez dowiązanie symboliczne - czyli można to zrobić używając opcji systemu operacyjnego. Ale tak taka zmiana byłaby faktycznie mile widziana - [ ] Files/search should allow more than one root directory

**Comment by andrzejchmiel3** [comment]
1. Ok, może coś źle robiłem, ale wydawało mi się że nie da się kliknąć dwa razy w SEARCH na nazwę tabeli żeby przeniosło na tę tabelę do SCHEMA, o ile się nie ma SCHEMA otwartego. A da się. Także wycofuję sugestię, jest ok.

**Comment by KrzysztofDusko** [comment]
oceń czy całość punktów jest OK.

**Comment by andrzejchmiel3** [comment]
Całość jest ok, dziękuję
