### ISSUE TITLE
Clicking column name (from results to SQL window) is hard

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#294]
Example below:
select 1 as i , 2 as longNameEasyToClick

We can click on column name in results, to have this name inserted to code window on cursor position. But to do that, we need to click exactly on text, which is often hard, especially in shorted column names. That's because the 'hitbox' where it works is very small. If i click a bit above text, or below, or on the left, it won't work. 

on screenshot, green represents area where clicking works, yellow is area where clicking won't do anything, but it should in my opinion
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/e4a3b0b5-47a2-462a-96cb-8cad7853d4d6)

It that's posssible, make larger 'clickable box' around text where i can click to paste column name

**Comment by KrzysztofDusko** [comment]
clicable area willbe extened in next update to : 
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/4f836168-0491-4690-a98e-d0cf37d6bb89)
