### ISSUE TITLE
refresh table list does not work for F4 and F6 features

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#295]
After creating new table, I'm using "refresh table list" on database so I can see new table (on the tree). But clicking it with F4 or F6 in code (or custom options in right click) does not work for that new table. It is unless i restart program, which is not ideal.

Please make this somehow refresh along with table list when clicking "refresh table list". Ideally, it would be nice to have some easier "refresh base for that table" on right click, so I won't have to refresh whole database after creating table.

**Comment by KrzysztofDusko** [comment]
bug this is fixed now - but about easier refresh method please fill another issue  - its nice idea but highly risky taking into account foreign keys
