### ISSUE TITLE
scroll bar auto-hiding is annoying

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#296]
I think it would be better to have scroll bar always visible (especially that on on bottom in results tab). Tight now it takes to long to find it, hover over, wait until it shows up, then start scrolling like I would normally would.

Additionally, it sometimes prevents me from clicking on last row, because hovering over last row makes scroll bar to appear on top of the row.

**Comment by KrzysztofDusko** [comment]
note than if you holds [Shift] scroling is horizontally witch can be usefull in this situation

**Comment by KrzysztofDusko** [comment]
Your opinion about annoying is really .. opinion. For me is ok :) but i agree with that auto hide is sometimes overrated. I maked horizontal scrool bar visible if  it will be accepted by other users it will be pernament change. For now i close this as completed

![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/2c7dab4f-49b5-458a-814a-4980a7dc21bd)
