### ISSUE TITLE
Odstęp miedzy liniami powinien być konfigurowalny

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/JustyBase#308]
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/eda65573-7e0b-4e7d-b68d-24893a00b652)

**Comment by KrzysztofVl** [comment]
+ belka powinna mieć opcje przycinania a nie "wrapowania"
![image](https://github.com/KrzysztofDusko/JustyBase/assets/135584450/4d94e5b7-844e-4a05-99ec-466dc98fd4fa)

**Comment by KrzysztofDusko** [comment]
![image](https://github.com/KrzysztofDusko/JustyBase/assets/69449360/e38f3fe0-82ff-4c0b-93f8-efdb980cc231)
