### ISSUE TITLE
CTRL+B always goes back to default, it should remember last width

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#316]
ctrl+B hides left panel, next ctrl+B shows it. But width of the panel is resetted by that operation. 
And that is annoying, for example, I'm using very wide left panel to see whole paths / names/  logs. This is why I'm using ctrl+b, to hide wide panel while i don't need it. But next ctrl+b make it short again, so i have to manually make it wider every time I'm using ctrl+B.
If possible, please make ctrl+B keep previous panel width

**Comment by KrzysztofDusko** [comment]
Case is known to me it's much more complex than looks like...

**Comment by KrzysztofDusko** [comment]
please check new version

**Comment by andrzejchmiel3** [comment]
It feels like it now has slight delay after using ctrl+B to show hidden panels, but it is far better anyway, thank you
