### ISSUE TITLE
query log - quality of life ideas, make it more legible

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#318]
Screenshot below, I'm running multiple selects  (some of them at once) in tab named "document 13"
```
select 1;
select 2;
select 3;
select 4;
select 5;
select 1/0;
```

![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/fc97ed3b-9430-47e1-8310-c2bc8c46e196)

It is quite unclear from log whats going on, I believe it could be far more legible, I have some ideas:
1. 'Document' column - is that even necessary here? If i switch to another tab, it has its own log. I would at least move it after main log column "Message"
2. Every F5 (run queries) start with "started" and ends with "finished". And everything inbetween has an indent. 
But when log is long enough, it's not that visible as it could, maybe use bold font for "started" and "finished"?
3. "started" and "finished" have another issue, usually "started" will be after "finished" which leads me to think they are one pair - process that started and just finished (especially if I don't remember what sort on dates is currently used). It would be nice to separate them, three ideas on how to do that:
a.With blank line after each "finished"
b. with horizontal line after each "finished" 
c. with highlighted blocks from start to finish, crude example below. Would especially work well with a. 
d. hightlighted block with slight borders, which is basically b+c
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/cf35e1a2-e6f3-460c-bd46-8918d284b4b1)
4. Less important, but it would also be nice to know that 'log hasn't ended yet', I mean that that query is still running, so there will be more in log soon.
Right now we have barely visible indicators that query is running, which are  progress bar and clickable red stop button instead of green play. But those are usually far away from log area, it's weird to look far away from log to see if I should expect more logs soon, if query has finished or not.
Maybe you could put some indicator in log that query is running, that log is not complete yet? Like some load circle:
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/9e22b8da-a563-461f-9c19-098a9839fd03)

**Comment by KrzysztofDusko** [comment]
i agree - log view in very poor. I made some changes now. Plese check and give your opinion.

**Comment by andrzejchmiel3** [comment]
Generally great attempt to make it more legible, although something is missing now in logs. I ran 
select 1; select 2
5 times. Now clicking on previous runs sometimes does not expand into details. Like below:
![obraz](https://github.com/KrzysztofDusko/JustyBase/assets/93384978/51e8d479-1f56-4ff6-8028-fed38b375c48)

**Comment by andrzejchmiel3** [comment]
And clicking on 'Message' column, previosly sorted by that column. Now it seems to sort by time, despite clicking on message.
I'm not sure what should it be doing after those changes, maybe just disable action on clicking on that column

**Comment by andrzejchmiel3** [comment]
Now I think it's good, legible enough, thank you for those upgrades.
